### PR TITLE
Testing Conversation History Interactor(s)

### PR DESCRIPTION
**Pull request by milkdromeda**
- Tested ConvHistInteractor and MsgSenderInteractor
     - ConvHistInteractor's test uses a mock database (InMemoryUserDataAccess)

### CODE REVIEW

**Review by Madhavan7 — DISMISSED** [review]
I like the use of anonymous classes in your tests, and adding assertions inside them.

**Review by sogolsahebi — COMMENTED** [review]
The overall design looks very clean. I Like the Conversation HistoryInputBoundary Interface following the Decency inversion and separation of the layers. Also, Using the conversation history class is a good choice for <DS> . my comment  is maybe to add documentating of class with their responsibility?
Just a reminder to complete the "send button" in the ChatView UI class, and let me know if you need help with.

**Review by sogolsahebi — APPROVED** [review]

**Review by emma0925 — COMMENTED** [review]
.

**Review by emma0925 — APPROVED** [review]
I think you code follows the clean architecture very well. It has all the key components. The ConvHistInteractor implements the InputBoundary and the controller creates the InputBondary.

**Pull request merged**
